name: monitoring

services:
  metrics-api:
    build: ./metrics-api
    env_file:
      - .env
    ports:
      - "3000:3000"
  grafana:
    image: grafana/grafana:13.1.0-25893932881
    container_name: grafana
    ports:
      - "5000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  grafana_data:
