name: Security

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Installation des dépendances
        run: yarn install

      - name: Audit des dépendances
        run: yarn audit --audit-level=moderate

      - name: Installation de Semgrep
        run: pip install semgrep

      - name: Analyse de code statique
        run: semgrep scan --config=auto .

      - name: Installation de git-secrets
        run: 
          yarn global add git-secrets && \
          git secrets --install

      - name: Scan des secrets
        run: git secrets --scan

      - name: Scan des secrets dans l'historique
        run: git secrets --scan-history